### ISSUE TITLE
TODO: Rewriting parts of the plugin

### ISSUE THREAD

**Issue by GLolol** [GLolol/Supybot-Weather#1]
- [ ] Fix almanac (`Error: KeyError: 'lownormal'`).
- [ ] Iron out unused variables/functions/etc.
- [ ] Fix the tests!
